#HTC DEVICES
add_lunch_combo ux_pico-userdebug
add_lunch_combo ux_golfu-userdebug

#NEXUS DEVICES
add_lunch_combo ux_mako-userdebug
add_lunch_combo ux_manta-userdebug
add_lunch_combo ux_tilapia-userdebug
add_lunch_combo ux_grouper-userdebug